### ISSUE TITLE
Multiverse and Inventory

### ISSUE THREAD

**Issue by BMXHashy** [ucchyocean/ReversiLab#6]
Hi there,
I'm using this plugin on my server (ksl-bmx.de), it's quite funny!
But I have a problem, if I came back from the Game, all my inventories are gone.
Is there a way to fix that?
I'm using Multiverse (incl. MV Inventory).
Thx,
Hashy

**Comment by ucchyocean** [comment]
Please use ReversiLab v1.0.1.
This issue has been fixed at issue #5 already.

And, don't write your request here. This is not request form. Please write it to BukkitDev page.
